#Disqus
#---
#layout: default
#comments: true
# other options
#---

# Site
name: 'raceto11'
description: 'A cuesports blog with a focus on English 8 ball pool.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'

#for use with github.io
#baseurl: '/raceto11'
#url: 'https://s2moore.github.io'
# for use with own domain
#url: 'https://your-domain.com'

# baseurl: '/raceto11'
url: 'https://raceto11.com'
#was disqus: 'demowebsite'
disqus: 'raceto11'
email: 'raceto11blog@gmail.com'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           raceto11
      site:           https://www.raceto11.com
      avatar:         /assets/images/avatar1.jpg
      bio:            "raceto11 is passionate about cuesports.  
                       We aim to provide regular features and stories from the world of 8 ball pool and cuesports
                       with reader participation.  Whether you play on a pro circuit, a county player, 
                       a club amateur, a leisure player or an armchair enthusiast.  We respect everyone's opinions.

                       If you have an article you'd like us to publish or any cuesport news then please contact us."
      email:          info@raceto11.com
      twitter:        https://twitter.com/raceto11

    #jane:
    #  name:           Jane
    #  site:           https://www.wowthemes.net
    #  avatar:         /assets/images/avatar2.jpg
    #  bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    #  email:          fakemail@gmail.com
    #  twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: raceto11
      avatar: /assets/images/8 ball rack - green cloth - Int-Rules Setup.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
